### ISSUE TITLE
Error: cannot convert string to float

### ISSUE THREAD

**Issue by gaohuiguo88** [TyrantLucifer/ssr-command-client#1]
as shown in the attached image

**Comment by TyrantLucifer** [comment]
The reason of this bug is because the ssr‘s node server or ip is not a normal link,and I hava fixed this bug,please download the resource or git pull master again.By the way,your ssr subscribe url is display in the image,I think you should change your ssr subscribe url so that the node info is secretive.Thanks very much that you use the ssr-command-client,if also have some bugs,please get in touch with me!

**Comment by gaohuiguo88** [comment]
Thank you for your remind! Pretty appreciate it!
